stages:
  - instalacao-das-dependencias
  - Testes

instalacao-das-dependencias:
  stage: instalacao-das-dependencias
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - apt-get install -y npm
    - npm install -g newman

testes-api:
  stage: Testes
  script:
    - newman run "test-api-automation.postman_collection.json"